export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Services } from './Services';
export { default as Features } from './Features';
export { default as Portfolio } from './Portfolio';
export { default as Testimonials } from './Testimonials';
export { default as Team } from './Team';
export { default as FAQ } from './FAQ';
export { default as Contact } from './Contact';
